### ISSUE TITLE
Economist App无法代理

### ISSUE THREAD

**Issue by haomuch** [ACL4SSR/ACL4SSR#106]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
Economist App无法通过ACL文件代理，虽然Economists的网站最近好像都解封了，但是App还是需要走全局代理才能下载新期刊

另外这个网站能否也加入代理列表：
https://www.mergersandinquisitions.com
一个投行求职相关的个人博客网站，不知道为什么居然也长期被封锁了

**Comment by haomuch** [comment]
补充一下，是gfwlist-banAD.acl文件

**Comment by haomuch** [comment]
banAD.acl也不行

**Comment by haomuch** [comment]
啊说错了，banAD.acl可以，但还是希望能修复gfwlist-banAD.acl

**Comment by BROBIRD** [comment]
Economist App 访问的URL能否提供一下？是否方便抓包？

**Comment by haomuch** [comment]
我也不知道Economist App现在访问的URL是哪个，但是很明显并非其官网地址。抓包啥的我不太会啊，站长可否安装一个试一下？可以用这个下载链接（订阅版，期刊免费下载，都是高品质经济学文章有兴趣也可以读一读）https://share.weiyun.com/a6b14c558fcc5def955c643abc39a774

**Comment by haomuch** [comment]
通过抓包工具，app访问的是computer-1.amazonaws.com(computer-1前面还有一串诸如ec2-34-227-250-100这样的字符串)，IP地址也不尽相同(如34.227.250.100:443)

**Comment by BROBIRD** [comment]
重点是`computer-1.amazonaws.com`前面的一串字符，抓包截图可以发一下吗？

**Comment by BROBIRD** [comment]
`*.computer-1.amazonaws.com`这样的域名，访问失败或无返回数据的那部分发一下

**Comment by haomuch** [comment]
部分下载时访问的IP前缀如下：
ec2-54-210-142-85
ec2-54-174-24-124
ec2-54-174-178-70
ec2-54-175-2-194
ec2-54-210-54-246

似乎每次下载访问的IP前缀都不同，只有前两位ec2-54是一致的，这种情况可以解决吗？
