### ISSUE TITLE
acl模式下gbroad翻译功能不可用

### ISSUE THREAD

**Issue by kljjh** [ACL4SSR/ACL4SSR#109]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
gbroad里的翻译功能显示无网络链接，切换全局模式正常，如何解决？

**Comment by BROBIRD** [comment]
抓包，查看此功能连接的域名

**Comment by Abner0802** [comment]
安卓的ss怎么用小白一个，刚用安卓一天
