### ISSUE TITLE
mytvsuper直播五个电视台不可用 点播可以用可以跳过广告 

### ISSUE THREAD

**Issue by lawlawlawlawlaw** [ACL4SSR/ACL4SSR#122]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

**Comment by lawlawlawlawlaw** [comment]
一开始以代理acl文件进入mytvsuper无法观看直播电视 显示黑屏 但如果先以ssr自带的绕过局域网和中国大陆或者全局进入软件先，然后再切换成acl文件，则可以收看直播且广告亦消除。

**Comment by BROBIRD** [comment]
请问可以请您抓包吗？我不太了解这个软件如何使用
