### ISSUE TITLE
instagram刷不出图片

### ISSUE THREAD

**Issue by rjyu** [ACL4SSR/ACL4SSR#124]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [x] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
打开instagram刷不出图片

**Comment by liolilin** [comment]
我也一直刷不出来，系统是安卓8.1，然后软件是ssr，用自带的全局还有其他的代理规则没问题用自定义ACL不行

**Comment by leosam1995** [comment]
我更新了一下 你更新了还不行吗

**Comment by liolilin** [comment]
我也更新了，不行

**Comment by leosam1995** [comment]
你是app刷新不出来还是网页刷新不出来
我网页看着能刷新啊

**Comment by liolilin** [comment]
网页一直都可以，就是app不行

**Comment by leosam1995** [comment]
那今晚抽空我下个app 看看

**Comment by liolilin** [comment]
好嘞，你是维护人员？

**Comment by leosam1995** [comment]
恩

**Comment by liolilin** [comment]
回复好及时，给力～💪👍

**Comment by leosam1995** [comment]
我试了一下app 可以看图片和视频啊  我用的是ssr 3.4.0.7版本的

**Comment by BROBIRD** [comment]
emmmm貌似3.4.0.6后面的都是个人编译的了……leo用的可能是我编译的版本？在我的GitHub里有下载

**Comment by liolilin** [comment]
我用的是，3.4.06版本的ssr

**Comment by BROBIRD** [comment]
有关代理的部分代码没有修改过，所以应该不是客户端的问题

**Comment by liolilin** [comment]
那奇怪了，3.4.06不行，你编译的可以

**Comment by BROBIRD** [comment]
这就非常奇怪了……

**Comment by liolilin** [comment]
我昨天换用3.4.07用自定义ACL可以，今天就又不行了😂

**Comment by rjyu** [comment]
可以了一段时间，现在又不行了，更新acl也没用，就是ins的app里有图片的地方是空白，ssr路由换成绕过国内就行
