### ISSUE TITLE
安卓系统使用SSRR，banAD.acl规则，汽车之家降速严重

### ISSUE THREAD

**Issue by qwerpoiugb** [ACL4SSR/ACL4SSR#133]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
汽车之家网站及APP，在banAD.acl规则下访问降速严重，希望更新直连
www.autohome.com.cn

**Comment by qwerpoiugb** [comment]
@BROBIRD 那我去问问SSRR的开发，谢谢。
