### ISSUE TITLE
Gmail的XOAuth2，貌似因为加了端口，所以不在gfw列表。

### ISSUE THREAD

**Issue by kn007** [ACL4SSR/ACL4SSR#140]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [x] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

Gmail的XOAuth2，貌似因为加了端口，所以不在gfw列表。

地址示例：imap.gmail.com:993

**Comment by BROBIRD** [comment]
什么情况下出现的访问问题？可否描述一下？

**Comment by kn007** [comment]
sms backup +(Android)
无法备份。

**Comment by kn007** [comment]
是的，软件，他原理是通过IMAP备份短信等内容到Gmail。直接Gmail客户端收件是正常的。
我把规则最后$去了就好了，其实也可以改一下正则支持端口就可以了，但是懒。。

**Comment by BROBIRD** [comment]
还真没意识到这个问题……我有空研究下 谢谢

**Comment by kn007** [comment]
客气了，非常感谢这个项目。

**Comment by daisuki4gh** [comment]
“我把规则最后$去了就好了，其实也可以改一下正则支持端口就可以了，但是懒。。”
@kn007 跟你遇到同样的问题，请教下如何修改正则，我尝试改成这样 `(^|\.)gmail\.com(:\d*)?$` 还是不行。（不会正则，照着网上搜索自己写的 。。）

**Comment by BROBIRD** [comment]
@daisuki4gh 
`(^|\.)gmail\.com(:)?(\d)*$`
试试看？

**Comment by daisuki4gh** [comment]
`#**********************************************************************
[proxy_list]

# MyList

(^|\.)gmail\.com(:)?(\d)*$
(^|\.)bit\.no\.com$`
@BROBIRD 您好，我用的这个gfwlist-banAD.acl，根据您的建议修改成如上所示，仍然不行。

**Comment by kn007** [comment]
`(^|\.)gmail\.com`

**Comment by daisuki4gh** [comment]
`$ grep -i gmail /Library/WebServer/Documents/gfwlist-banAD.acl
(^|\.)gmail\.com`

**Comment by kn007** [comment]
你是SS还是SSR

**Comment by daisuki4gh** [comment]
@kn007，ss。
刚测试如果用shadowsocks自带的gfw模式也可以正常同步。虽然第一次报错，再点一次就OK。

`06-29 09:09 备份请求 (手动)
06-29 09:09 开始备份 (MANUAL)
06-29 09:09 正在备份 (2 条短信, 0 条彩信, 0 条通话记录)
06-29 09:09 正在备份 (2 条短信, 0 条彩信, 0 条通话记录)
06-29 09:10 一般错误：Gmail IMAP 临时性错误，请稍后再试 (exception: com.fsck.k9.mail.MessagingException: Unable to get IMAP prefix, underlying=javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x7888d35780: I/O error during system call, Connection reset by peer)
06-29 09:10 备份已完成
06-29 09:10 备份请求 (手动)
06-29 09:10 开始备份 (MANUAL)
06-29 09:10 正在备份 (2 条短信, 0 条彩信, 0 条通话记录)
06-29 09:10 备份已完成
`

**Comment by kn007** [comment]
SS的客户端不行，SSR的就可以🙄

**Comment by BROBIRD** [comment]
@daisuki4gh Telegram 用的是 IP 地址连接的，我倒是想请教你怎么参考？

**Comment by BROBIRD** [comment]
@kn007 很抱歉我们无法对除 SSR 以外的客户端提供可用性保证。

**Comment by daisuki4gh** [comment]
@BROBIRD 请教不敢当，完全是外行的一个想法吧：类似telegram那样，把 IMAP.google.com 的IP抓出来，然后放进GFW强制走代理列表。
https://blog.phpgao.com/telegram_ip.html

**Comment by BROBIRD** [comment]
@daisuki4gh 完全不现实，你查查看Google有多少个IP？
