### ISSUE TITLE
能否在默认代理模式中将GCM/FCM直连，主要是服务器IP的问题

### ISSUE THREAD

**Issue by ghost** [ACL4SSR/ACL4SSR#146]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
由于SS/SSR设计缘故，服务器/客户端都有长连接设置，好像SSR客户端默认就是120s，在连接中默认取双方两个数值较小者即120s，GCM/FCM就这样每隔两分钟被掐掉，多次重连后就不在连接，推送也就没了。
但GCM/FCM本身没被完全墙掉，推送服务器有的被墙了IP有的没有，所以使用gfwlist（黑名单）可以找到可用的IP直连使用推送，是能用的。
但在白名单模式下连接服务器IP会走代理通道，然后就120s重连了（有的app用gfwlist没法用比如textnow，还有我不会抓包什么的。。。这些都是我在网上找的资料）
所以要在白名单模式下用上GCM/FCM要同时在[bypass_list]写上域名跟IP
下面是我自己模仿写的正则表达式
问题来了，域名好写，IP会变化，有对IP模糊匹配的法子么，像`64.233.*.188`, `74.125.*.188`要怎么表达，不想整天一个个查dns慢慢加，有好办法么（试着直接^.*\.188$匹配尾数188的IP貌似没用啊😂）
推送服务器好像只有`mtalk.google.com/mtalk4.google.com/alt【数字1-8】-mtalk.google.com`
```
Google FCM
(^|\.)mtalk\d?\.google\.com$
(^|\.)alt\d?-mtalk\.google\.com$
Google FCM IP
64.233.170.188
64.233.177.188
64.233.179.188
64.233.185.188
64.233.186.188
64.233.187.188
64.233.188.188
64.233.189.188
64.233.190.188
66.102.1.188
74.125.23.188
74.125.71.188
74.125.126.188
74.125.129.188
74.125.136.188
74.125.192.188
74.125.203.188
74.125.204.188
108.177.13.188
108.177.97.188
108.177.104.188
108.177.125.188
173.194.66.188
173.194.76.188
173.194.199.188
173.194.218.188
209.85.202.188
209.85.203.188
209.85.144.188
209.85.147.188
```

**Comment by BROBIRD** [comment]
首先SSR客户端默认超时时间是600s，请检查你的服务端配置
其次，`(^|\.)google\.com`已经包含了你所说的域名。

**Comment by MatcherAny** [comment]
这是希望GCM服务的mtalk.google.com域名走白名单，我也有同样需求
