### ISSUE TITLE
增加对[即刻app]的直连域名请求

### ISSUE THREAD

**Issue by TsXcd** [ACL4SSR/ACL4SSR#152]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
日常使用的时候发现即刻的浏览会走非直连，希望可以增加即刻APP的相关域名到相关acl的直连中，自己尝试了一下增加以下规则直连即可，谢谢。

(^|\.)\w*ruguoapp\w*\.\w*$

**Comment by leosam1995** [comment]
下次更新加上
