### ISSUE TITLE
添加upmedia.mg

### ISSUE THREAD

**Issue by huanglittleming** [ACL4SSR/ACL4SSR#156]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [x] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [ ] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
添加upmedia.mg域名
