### ISSUE TITLE
关于apkpure安卓客户端的域名

### ISSUE THREAD

**Issue by LittleGrocery** [ACL4SSR/ACL4SSR#162]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [x] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
apkpure客户端于10.14日被封禁，原来的gfwlist规则只包含桌面网页端的规则，故提交以下关于移动端的规则
1.提交域名 m.apkpure.com image.winudf.com

**Comment by leosam1995** [comment]
更新添加apkpure\.com 
winudf没有被拦截 就没添加
