### ISSUE TITLE
提交广告域名

### ISSUE THREAD

**Issue by MurphyWhite** [ACL4SSR/ACL4SSR#165]
* 有关此issue的规则名称：
- [x] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [x] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
mi.gdt.qq.com
pgdt.ugdtimg.com
sdk.e.qq.com
广告域名

**Comment by BROBIRD** [comment]
可以确定这些域名不存在非广告的用途吗？

**Comment by MurphyWhite** [comment]
可以确定 *.gdt.qq.com 是广告域名，从 ublock 的 chn：EasyList China 规则中看到此域名，见下图
pgdt.ugdtimg.com 与 sdk.e.qq.com 暂时无法确定是否具有非广告用途

广告来源
Android 动漫之家 启动页广告，章节最后一页、再往后翻的评论页面
Android 漫画人 启动页广告

[广告链接](http://mi.gdt.qq.com/gdt_mview.fcg?fc=1&datatype=2&posh=960&count=2&adposcount=1&spsa=1&r=0.9837853259068555&posw=640&ext=%7B%22req%22%3A%7B%22m2%22%3A%22e3f5536a141811db40efd6400f1d0a4e%22%2C%22m3%22%3A%22f48facab49f47f794402d001571e7e62%22%2C%22m6%22%3A%225a1d0f4d066b31d5563f3657ec923d66%22%2C%22muidtype%22%3A3%2C%22muid%22%3A%22e3f5536a141811db40efd6400f1d0a4e%22%2C%22placement_type%22%3A4%2C%22render_type%22%3A1%2C%22conn%22%3A1%2C%22carrier%22%3A0%2C%22loc_src%22%3A5%2C%22support_app_landing_page%22%3A1%2C%22c_os%22%3A%22android%22%2C%22c_osver%22%3A%227.1.1%22%2C%22c_pkgname%22%3A%22com.dmzj.manhua%22%2C%22c_device%22%3A%22Nexus%209%22%2C%22c_devicetype%22%3A2%2C%22c_mf%22%3A%22htc%22%2C%22c_ori%22%3A0%2C%22c_w%22%3A1536%2C%22c_h%22%3A2048%2C%22sdkver%22%3A%224.13.576%22%2C%22tmpallpt%22%3Atrue%2C%22postype%22%3A4%2C%22deep_link_version%22%3A1%2C%22c_sdfree%22%3A1384648704%2C%22c_market%22%3A%22%22%2C%22c_hl%22%3A%22zh%22%2C%22gdtid%22%3A%22_1541685909954212%22%2C%22scs%22%3A%2200015a8a3704%22%2C%22ast%22%3A%7B%22br%22%3A%22google%2)

![image 2018-11-08 22 44 41](https://user-images.githubusercontent.com/9551931/48205840-e1ac2900-e3a7-11e8-8f2d-cc624f1e452d.jpg)

**Comment by leosam1995** [comment]
gdt已添加 更新加上

**Comment by Awu1d** [comment]
你好，最近几天受困于斐讯路由器的广告骚扰，实在受不了了，自行进行了网络抓包，发现广告域名为ck.kejet.net，查询大佬编写的规则，发现ACL文件内已包含了关键字“kejet”的拦截项，但实际上未对其进行屏蔽拦截，恳请大佬在下次更新时处理一下，辛苦大佬了
