### ISSUE TITLE
Youtube广告域名提交

### ISSUE THREAD

**Issue by LittleGrocery** [ACL4SSR/ACL4SSR#168]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [x] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
在youtube的https://www.youtube.com/yts/jsbin/desktop_polymer-vflPwCF-V/desktop_polymer.js 下找到以下这段代码，经我初步分析应该就是广告域名，无奈能力有限，不知道如何匹配这些域名，比如moatads前还会有任意字符，可能是1.moatads 也可能是 2.moatads 故提交到这边希望可以讨论下怎么屏蔽这些广告

/^https?:\/\/([^.]*\.moatads\.com\/|e[0-9]+\.yt\.srs\.doubleverify\.com|pagead2\.googlesyndication\.com\/pagead\/gen_204\?id=yt3p&sr=1&|pm\.adsafeprotected\.com\/youtube|pm\.test-adsafeprotected\.com\/youtube|youtube[0-9]+\.moatpixel\.com\/)/,SZ=/^https?:\/\/(www\.google\.com\/pagead\/sul|www\.google\.com\/pagead\/xsul|www\.youtube\.com\/pagead\/psul|www\.youtube\.com\/pagead\/slav|www\.youtube\.com\/pagead\/sul)/,TZ=/^https?.*#ocr$|^https?:\/\/(aksecure\.imrworldwide\.com\/|cdn\.imrworldwide\.com\/|secure\-..\.imrworldwide\.com\/)/

**Comment by leosam1995** [comment]
下次更新添加
