### ISSUE TITLE
纽约时报中文版无法加载菜单和文章

### ISSUE THREAD

**Issue by liurui39660** [ACL4SSR/ACL4SSR#175]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl（纽约时报被GFW屏蔽所以没有测试）
- [x] banAD.acl
- [ ] fullgfwlist.acl（没有反广告所以没有测试）
- [x] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [ ] nobanAD.acl（没有反广告所以没有测试）
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

安卓手机上的纽约时报中文版在开启上述acl文件后无法正常加载菜单和文章，显示`检查版本信息失败，请检查网络连接TypeError: Network request failed`，切换到其他路由文件后恢复正常

**Comment by leosam1995** [comment]
我看了一下 没问题啊 
能提供被屏蔽的网址吗
