### ISSUE TITLE
请求更新SSR#C规则

### ISSUE THREAD

**Issue by zh-sg** [ACL4SSR/ACL4SSR#178]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
跟广告过滤无关，我只需要有同步fullgfwlist的user.rule就很满足了。
问题跟ip段有关，pac貌似不支持ip段，某些软件（Telegram）在gfwlist-pac模式下就连不上。
acl超好用，然而SSR桌面端想支持真是有生之年系列了。。。
不要提自定义代理，就是因为不想每次在公网开ssr还要顺便改telegram设置才想到发这个的
希望能恢复更新，出个fullgfwlist-user.rule也是极好的。
ps: 如果更新请顺便把hosts那一部分删除了，指定hosts导致维基百科用不了

**Comment by BROBIRD** [comment]
Telegram 直接设置用1080端口的代理其实就可以了……个人觉得这不是很急迫的需求……
维基百科的hosts后面会删除……
之前计划写代码自动更新的……一直咕咕咕……

**Comment by moritasan** [comment]
这个旧版本的规则似乎屏蔽了tor节点

**Comment by Loyalsoldier** [comment]
@zh-sg 
SSR 是支持 ACL 的。

在 SSR `高级设置`里修改 `ACL GFW List 列表 URL` 为 `ACL4SSR` 的 ACL 网址。然后在 SSR 的`代理设置`中点击`更新全部白名单`，最后 SSR 的代理模式选择 `ACL 自动`

**Comment by BROBIRD** [comment]
> 
> 
> @zh-sg
> SSR 是支持 ACL 的。
> 
> 在 SSR `高级设置`里修改 `ACL GFW List 列表 URL` 为 `ACL4SSR` 的 ACL 网址。然后在 SSR 的`代理设置`中点击`更新全部白名单`，最后 SSR 的代理模式选择 `ACL 自动`

并不是所有人都是Mac客户端
