### ISSUE TITLE
mac系统下不能收国外邮箱邮件

### ISSUE THREAD

**Issue by y1han** [ACL4SSR/ACL4SSR#188]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
RT, 在自带app mail中不能够连接gmail以及海外iCloud邮箱

**Comment by BROBIRD** [comment]
最好提供一下抓包结果，我们暂时没有OSX设备，无法定位问题

**Comment by Loyalsoldier** [comment]
要同时开启 macOS 的 SOCKS 代理、HTTP 代理和 HTTPS 代理，经测试正常收发邮件。
