### ISSUE TITLE
请更新直连域名列表

### ISSUE THREAD

**Issue by LeMiao** [ACL4SSR/ACL4SSR#207]
* 有关此issue的规则名称：
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

---

* 您要反馈的问题：
您好，我使用上面的规则无法连接到我的域名下的部分后台服务，因为它们需要回源。
请问可以将域名 "*.anyi.in" 加入直连列表吗，谢谢！
同时，我校校内将 IP 段 "172.x.x.x" 作为校内 DNS 及校内服务地址，现在开启代理后访问校内服务会被拒绝。据我所知，很多高校都将 "172.x.x.x" "192.x.x.x" 作为自己的内网服务地址。
请问可以将 IP 段 "172.x.x.x" 加入直连列表吗，再次感谢！

**Comment by BROBIRD** [comment]
https://github.com/ACL4SSR/ACL4SSR/blob/3ce6416385cf2a53460094ae45d7a26cab9fd2a5/banAD.acl#L1857-L1874

> 同时，我校校内将 IP 段 "172.x.x.x" 作为校内 DNS 及校内服务地址，现在开启代理后访问校内服务会被拒绝。据我所知，很多高校都将 "172.x.x.x" "192.x.x.x" 作为自己的内网服务地址。
请问可以将 IP 段 "172.x.x.x" 加入直连列表吗，再次感谢！
