### ISSUE TITLE
Google play 下载应用失败

### ISSUE THREAD

**Issue by LaoZhang666** [ACL4SSR/ACL4SSR#208]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
开发者成员你们好，目前我遇到的一个问题是，所有服务均正常，去广告，代理gfw认证网站，唯一的一个问题是Google play商店下载应用，play商店可以正常进入，但是无法下载，下载应用一开始显示download pending，随后一直downloading，但是始终不能正常下载。除此此外，所有一切正常，Youtube观看，Google搜索均无问题，搜索过历史issues，但应该不是相同问题，谢谢。

**Comment by BROBIRD** [comment]
无法复现

**Comment by LaoZhang666** [comment]
宽带与移动数据均出现相同问题，无法更新，无法下载。是否需要我提供其它信息？谢谢。

**Comment by BROBIRD** [comment]
用了分应用代理功能吗？

**Comment by LaoZhang666** [comment]
没有

**Comment by LaoZhang666** [comment]
> 用了分应用代理功能吗？

没有。

**Comment by BROBIRD** [comment]
现有信息无法定位问题……有什么其他的信息吗

**Comment by LaoZhang666** [comment]
> 现有信息无法定位问题……有什么其他的信息吗

刚刚试了一下，将路由设置改为全局或绕过中国大陆也都会出现此问题，可能不是你们的ACL文件问题，抱歉。

**Comment by nictse2013** [comment]
之前可以么？
https://github.com/shadowsocksrr/shadowsocksr-android/issues/246
我的情况参考下
