### ISSUE TITLE
新浪微博的登录被屏蔽了

### ISSUE THREAD

**Issue by lizhaode** [ACL4SSR/ACL4SSR#55]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为“x”以勾选)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
屏蔽规则中  
(^|\.)tjs\.sjs\.sinajs\.cn$
这个地址的屏蔽会影响网页版的新浪微博的登录

表现就是，电脑上打开新浪微博，点击登录，不弹出登录框

**Comment by BROBIRD** [comment]
您使用的是OS X吗？

**Comment by lizhaode** [comment]
是的，这个和操作系统有关系嘛？

**Comment by lizhaode** [comment]
还有这个
(^|\.)(fav|m|redirect|srd|tns)\.simba\.taobao\.com$

redirect.simba.taobao.com

这个地址是百度搜索天猫，带有官方标签的第一个结果的跳转地址，被屏蔽之后，打不开的

**Comment by BROBIRD** [comment]
不好意思，暂时没有找到Mac设备测试，处理时间可能会长一些，请您谅解

**Comment by lizhaode** [comment]
这个网址和操作系统有关？win上边新浪微博的登录不是走这个地址吗？

**Comment by BROBIRD** [comment]
`redirect.simba.taobao.com`是所有带有推广的跳转链接的域名，所以暂时不考虑删除此条
`tjs.sjs.sinajs.cn`经过调查，暂时移除。
