### ISSUE TITLE
百度新闻图片打不开

### ISSUE THREAD

**Issue by nmyggg** [ACL4SSR/ACL4SSR#56]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
chrome for android
打开百度首页然后下拉，　图片点击后打不开

**Comment by BROBIRD** [comment]
`feed.baidu.com`是百度推广相关的域名，所以进行了屏蔽。
