### ISSUE TITLE
Windows10应用商店无法显示

### ISSUE THREAD

**Issue by cliffzhou** [ACL4SSR/ACL4SSR#57]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
第一次使用此Windows版C#客户端的规则，WIndows10是秋季创作者更新版本1709.
我的操作：在替换user.rule规则文件到ssr文件夹后，选择了全局模式+代理规则/用户自定义。
症状：WIndows10应用商店无法显示页面，无法列出已安装应用或更新应用，甚至无法显示我的用户头像。
关闭代理后，一切正常。切换为PAC模式，也正常。

**Comment by BROBIRD** [comment]
您好，可以复现该问题，但是我无法定位问题，暂时无法修复，建议您暂时在打开应用商店的时候关闭代理开关。

**Comment by zh-sg** [comment]
这个模式使用 WindowsLoopbackManager 启用一下就能联网了
