### ISSUE TITLE
10月30日，即刻app走了代理

### ISSUE THREAD

**Issue by stonereese** [ACL4SSR/ACL4SSR#60]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [x] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：使用fullgfwlist.acl,即刻app，不能连接

**Comment by BROBIRD** [comment]
这个规则不含有屏蔽规则啊。。。其他规则试过吗？是否正常？

2017年10月30日 21:48，"stonereese" <notifications@github.com>写道：
