### ISSUE TITLE
fullgfwlist.acl最近没有在同步了？提交给gfwlist的新网址无法更新。

### ISSUE THREAD

**Issue by s-mao** [ACL4SSR/ACL4SSR#61]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [x] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

**Comment by BROBIRD** [comment]
您好，不是实时同步的

2017年10月30日 22:26，"s-mao" <notifications@github.com>写道：
