### ISSUE TITLE
微信腾讯新闻公众号内容打开貌似走了代理以及手机淘宝发消息缓慢

### ISSUE THREAD

**Issue by wqtty** [ACL4SSR/ACL4SSR#63]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为“x”以勾选)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
1.微信腾讯新闻公众号内容打开貌似走了代理
2.手机淘宝发消息缓慢，貌似也走了代理

**Comment by BROBIRD** [comment]
请使用分应用代理

2017年11月3日 10:05，"wqtty" <notifications@github.com>写道：

**Comment by wqtty** [comment]
安卓SSRR在miui 9上分应用代理不好使，请参见
https://github.com/shadowsocksrr/shadowsocksr-android/issues/22

**Comment by BROBIRD** [comment]
我们尽量找出有问题的域名吧
叫你用MIUI（滑稽
您方便用Wiki中提及的方法测试一下相关的域名吗？谢谢！

2017年11月3日 11:47，"wqtty" <notifications@github.com>写道：

**Comment by wqtty** [comment]
个人感觉miui有本地化无人能及，也是我路转粉的原因

**Comment by BROBIRD** [comment]
有人说7.11.2修复了 你看一下

**Comment by wqtty** [comment]
果然修复了，多谢
