### ISSUE TITLE
知乎安卓app里面问题标题下方经常有横幅广告

### ISSUE THREAD

**Issue by ShureCool** [ACL4SSR/ACL4SSR#64]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
知乎app里面问题标题下方有广告，而且回答走了代理

**Comment by BROBIRD** [comment]
您好，您是如何判断回答走了代理的？能否提供一下截图？谢谢！

2017年11月11日 02:00，"ShureCool" <notifications@github.com>写道：

**Comment by leosam1995** [comment]
知乎所有的域名都加了直连了啊，有网址吗？

**Comment by BROBIRD** [comment]
应该说这个规则是默认直连的，除非下面有代理规则，理论上不应该

2017年11月11日 14:24，"leosam1995" <notifications@github.com>写道：
