### ISSUE TITLE
两条腾讯广告域名，常用于app广告

### ISSUE THREAD

**Issue by cxlg325** [ACL4SSR/ACL4SSR#68]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [x] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

mi.gdt.qq.com
sdk.e.qq.com

**Comment by BROBIRD** [comment]
是否有截图或者抓包信息提供？谢谢！

**Comment by cxlg325** [comment]
<img src=http://chuantu.biz/t6/139/1510571762x2890191835.jpg />

**Comment by cxlg325** [comment]
<img src=http://chuantu.biz/t6/139/1510571912x2890191835.jpg />

**Comment by BROBIRD** [comment]
`*.e.qq.com`本来就有了，`*.gdt.qq.com`加上了
