### ISSUE TITLE
1688app加载不了图片

### ISSUE THREAD

**Issue by ELOVSA** [ACL4SSR/ACL4SSR#79]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
阿里巴巴1688app图片无法显示

**Comment by BROBIRD** [comment]
请补充说明

**Comment by ELOVSA** [comment]
![_20171201110508](https://user-images.githubusercontent.com/33925014/33466251-904a1a6e-d687-11e7-8c9f-abcd9b141067.jpg)
![_20171201110457](https://user-images.githubusercontent.com/33925014/33466238-88d60fd6-d687-11e7-9d6a-528dd4c83007.jpg)

**Comment by ELOVSA** [comment]
首页图片，商品图片，聊天图片都无法加载。

**Comment by ELOVSA** [comment]
请问，这个问题可以解决吗？

**Comment by leosam1995** [comment]
我发现没拦截啥图片啊 你能给个呗拦截的图片地址么

**Comment by BROBIRD** [comment]
@leosam1995 确实拦截了，得抓个包看一下 可能是某个图片CDN域名在屏蔽列表里

**Comment by leosam1995** [comment]
@BROBIRD  你排查一下 我看了一下 1688里面 没拦截的域名里面啊

**Comment by ELOVSA** [comment]
这个图片拦截连聊天记录的图片都看不了

**Comment by leosam1995** [comment]
@ELOVSA  你不用ssr  直接看看 用wiki那里的抓包方式 抓一下图片链接 发我一下 我看看

**Comment by BROBIRD** [comment]
在上课，可能得晚上才有时间排查，你们先看一下

**Comment by ELOVSA** [comment]
不会抓包😭

**Comment by ELOVSA** [comment]
有空处理下呀

**Comment by leosam1995** [comment]
今天看看吧

**Comment by leosam1995** [comment]
没发现啥问题啊 我挂着代理 也能加载啊

**Comment by ELOVSA** [comment]
gfwlist-banAD.acl，你用的这个吗？我这不行

**Comment by leosam1995** [comment]
我用banAD.acl，你再更新一下 ，要是还有问题，我就没法了 因为我抓包了一下  没有被拦截的域名

**Comment by ELOVSA** [comment]
还是有问题。而且这个问题很奇怪，如果图片在详情页里面是可以加载的，但是在首页焦点图位置的图片就加载不出来。

**Comment by leosam1995** [comment]
那没辙了 跟我一样 用banAD.acl吧
都差不多

**Comment by ELOVSA** [comment]
看来只能这样了
