### ISSUE TITLE
SS原版自定义规则无法Google Play无法下载，无法查看Google地图

### ISSUE THREAD

**Issue by huaxianyan** [ACL4SSR/ACL4SSR#83]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [x] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
讲fullgfwlist.acl加入SS原版的自定义规则里，SS节点中选择自定义规则模式，Google Play无法更新，Google地图以及使用Google地图的第三方APP都无法显示。Google搜索正常运作，YouTube可以观看

**Comment by BROBIRD** [comment]
有没有抓个包看看？我最近有点忙，没时间测试了= =
我记得play相关域名都加进去了

**Comment by huaxianyan** [comment]
@BROBIRD Android上有什么比较简单的抓包方法？我找了一些都是建立VPN的方式，这样SS就用不了了，抓了没意义了吧？

**Comment by BROBIRD** [comment]
@huaxianyan 试试看在电脑上开ss，然后开热点给手机，填一下代理，应该就能在手机上抓包了，看一下访问了哪些域名，我自己使用是没有出现过问题

**Comment by huaxianyan** [comment]
@BROBIRD 重新测试了一下好像都不能运作了，我是只添加了acl的链接进去。还是说要手动把里面的内容添加进去？

**Comment by BROBIRD** [comment]
原版添加URL即可

**Comment by huaxianyan** [comment]
还是不行，我汇报一下我这边的情况

手机是Nexus 6P，rom是官方的8.1，SS是play上的原版 4.3.5版本，没申请beta

然后节点信息配置好，没开启远程DNS解析，规则选择自定义，在第二项自定义规则里选择添加链接，然后复制链接https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/fullgfwlist.acl进去，添加完成

之后再启动SS

因为家里的路由器有全局科学上网，所以我是用流量测试的，魔都电信4G网络，可以直接打的开上面的ACL链接

**Comment by BROBIRD** [comment]
具体是到哪一步出问题了？有没有其他的症状！

**Comment by huaxianyan** [comment]
以上那些步骤就是我的操作步骤，然后感觉ACL规则没生效，SS不能让程序走代理

我试着点了SS原版的添加中国地区无法访问的规则，可以正常使用，所以自定义规则是可以生效的

就是不知道为什么单独加载这个ACL不生效，感觉所有的链接都是直连，包括需要翻墙的那些域名

**Comment by BROBIRD** [comment]
那我就不知道原因了。。。另外什么叫直链？？

**Comment by huaxianyan** [comment]
我想表达的意思就是SS里代理的程序直接向目标请求，而不是通过代理去请求，直接连接

**Comment by BROBIRD** [comment]
额，能否发个图看一下，我实在是没法定位问题，找了朋友问，他说你的操作应该是没问题的

**Comment by huaxianyan** [comment]
[img]http://ww1.sinaimg.cn/large/6c41674cgy1fmk8rqc1oej21401z4dm5.jpg[/img]

**Comment by BROBIRD** [comment]
老哥，下次换个图床。。。另外我看不懂日语啊

**Comment by BROBIRD** [comment]
你貌似开了分应用代理？

**Comment by huaxianyan** [comment]
对，开的分应用代理……

**Comment by BROBIRD** [comment]
那那些应用开了代理没。。。

**Comment by huaxianyan** [comment]
开了，并且我尝试关闭分应用代理，也无效……

**Comment by BROBIRD** [comment]
这。。。。。你要不暂时直接复制文件内容导入吧

**Comment by huaxianyan** [comment]
我好像解决了，编辑规则里有3个

URL/子网/域名 PCRE 正则表达式
域名及其子域名
URL

我之前都选的是第一个，以为就是URL，没注意重点是落在正则表达式上面

可以close了，我的问题，打扰这么久真是抱歉

**Comment by BROBIRD** [comment]
（捂脸
你也没提到这个，我也没想到是这个原因

**Comment by huaxianyan** [comment]
因为添加的时候，那边直接显示URL/子网/域名XXXX没显示全

我以为是在这里添加，所以都是点加号直接粘贴链接就结束了
