### ISSUE TITLE
使用去广告版 滴答清单无法连接

### ISSUE THREAD

**Issue by xream** [ACL4SSR/ACL4SSR#85]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

banAD.acl  滴答清单无法连接
nobanAD.acl  滴答清单可以连接

抓包看到这些请求: 
 
![image](https://user-images.githubusercontent.com/1210282/33795191-c78a287a-dd17-11e7-953c-2076678de07a.png)
