### ISSUE TITLE
dilidili被屏蔽了进不去，然后淘宝自动走代理

### ISSUE THREAD

**Issue by MundaneDefoliation** [ACL4SSR/ACL4SSR#86]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：dilidili被屏蔽了进不去，然后淘宝自动走代理

**Comment by MundaneDefoliation** [comment]
网址
http://www.dilidili.wang
http://m.dilidili.wang

**Comment by BROBIRD** [comment]
本人测试没有发现此问题。。。请提供更详细的信息

**Comment by MundaneDefoliation** [comment]
![](http://oxgldbgt4.bkt.clouddn.com/Screenshot_2017-12-11-12-31-42-515_Chrome.png)

**Comment by MundaneDefoliation** [comment]
就像这样，换成ssr自带的就可以进去。

**Comment by BROBIRD** [comment]
![](https://i.imgur.com/9Qq0L1E.jpg)

**Comment by MundaneDefoliation** [comment]
难道是人品问题，想问一下你在用什么DNS。。。

**Comment by BROBIRD** [comment]
@MundaneDefoliation ChinaDNS:114.114.114.114:53 DNS:8.8.8.8:53

**Comment by MundaneDefoliation** [comment]
我把dilidili给加到remote DNS列表里就可以了，难道DNS被污染了。 。。

**Comment by BROBIRD** [comment]
@MundaneDefoliation 啥叫remotedns列表。。。

**Comment by MundaneDefoliation** [comment]
[remote_dns] 远程 DNS 解析 -不加使用本地 DNS
。。。就是这个。。

**Comment by BROBIRD** [comment]
@MundaneDefoliation 这个是全局属性，不是规则属性，加了这一行之后所有解析走代理，你考虑清楚。

**Comment by MundaneDefoliation** [comment]
。。。啊，这不是你的里面自带的吗。。

**Comment by BROBIRD** [comment]
@MundaneDefoliation 啥。。。。

**Comment by MundaneDefoliation** [comment]
https://github.com/ACL4SSR/ACL4SSR/blob/master/gfwlist-banAD.acl

你的这个文件的最后。。。

**Comment by BROBIRD** [comment]
蛋疼，忘了改了，之前一个错误的Pull Request里的

**Comment by MundaneDefoliation** [comment]
。。。
