### ISSUE TITLE
steam的服务

### ISSUE THREAD

**Issue by uoox** [ACL4SSR/ACL4SSR#96]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [x] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
steam在国内访问不了了，可以更新进去欧

**Comment by BROBIRD** [comment]
稍等几天，这几天有事

**Comment by leosam1995** [comment]
ok 已经添加

**Comment by Chthol1y** [comment]
steam的代理会影响到购买，导致跨区吗？
